name: flutter_project_booster
description: A CLI tool to scaffold Flutter project structure and update pubspec.yaml.
version: 0.0.7
homepage: https://github.com/3boodev/flutter_project_booster
repository: https://github.com/3boodev/flutter_project_booster

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  yaml: ^3.1.2
  path: ^1.9.0
  args: ^2.4.2
  archive: ^3.1.2

dev_dependencies:
  test: ^1.24.0

executables:
  flutter_project_booster: flutter_project_booster

# Optional: You can define topics (for pub.dev discoverability)
topics:
  - flutter
  - cli
  - assets
  - cleanup
  - optimization