name: flutter_project_booster
description: A CLI tool to scaffold Flutter project structure and update pubspec.yaml.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  yaml: ^3.1.2
  path: ^1.9.0

dev_dependencies:
  test: ^1.24.0

executables:
  flutter_project_booster: flutter_project_booster
